# Generated by Django 4.1.9 on 2023-05-08 06:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(max_length=255, verbose_name='Order address')),
                ('order_date', models.DateTimeField(blank=True, verbose_name='Order date')),
                ('payment_deadline', models.DateTimeField(blank=True, verbose_name='Payment deadline')),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Order summary price')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Id order paid?')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'db_table': 'Common_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product price')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Product photo')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='thumbnails', verbose_name='Product thumbnail')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.productcategory', verbose_name='Product category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Product seller')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Common_product',
            },
        ),
        migrations.CreateModel(
            name='OrderProductListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'Common_order_product_list_item',
            },
        ),
    ]
